# -*- coding: utf-8 -*-
"""roadaccident.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmpWPL11CQ9KYTAuz1MkxmNMbVVAdn01
"""

pip install pandas scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

# Load the dataset
data = pd.read_csv('road_accidents.csv')

# Independent variables
X = data[['Weather_Conditions', 'Road_Surface_Conditions', 'Lighting_Conditions',
          'Number_of_Vehicles', 'Number_of_Casualties', 'Speed_Limit']]

# Dependent variable
y = data['Accident_Severity']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the model
model = LinearRegression()
model.fit(X_train, y_train)

# Save the model
with open('accident_severity_model.pkl', 'wb') as file:
    pickle.dump(model, file)

# Load the saved model
with open('accident_severity_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Corrected hypothetical scenario with all required feature columns
example_data = pd.DataFrame({
    'Weather_Conditions': [1],
    'Road_Surface_Conditions': [0],
    'Lighting_Conditions': [1],
    'Number_of_Vehicles': [2],
    'Number_of_Casualties': [1],
    'Speed_Limit': [50]
})

# Predicting accident severity
predicted_severity = loaded_model.predict(example_data)
print("Predicted Accident Severity:", predicted_severity[0])